# Test cases generated by ChatGPT

import torch
import pytest

from densification import (
    densify,
    grad_threshold,
    size_threshold,
    split_scale,
    prune_opacity,
)


# ---------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------

def make_gaussians(mu, scale, opacity, color=None, theta=None):
    """
    Construct the tuple expected by densify().

    Arguments are specified in their intuitive forms:
        scale   -> converted to log_s
        opacity -> converted to op_raw logits
    """
    mu = torch.tensor(mu, dtype=torch.float32)
    scale = torch.tensor(scale, dtype=torch.float32)

    N = mu.shape[0]

    log_s = torch.log(scale)

    if theta is None:
        theta = torch.zeros(N, dtype=torch.float32)
    else:
        theta = torch.tensor(theta, dtype=torch.float32)

    if color is None:
        color = torch.zeros(N, 3, dtype=torch.float32)
    else:
        color = torch.tensor(color, dtype=torch.float32)

    opacity = torch.tensor(opacity, dtype=torch.float32)
    op_raw = torch.logit(opacity)

    return mu, log_s, theta, color, op_raw


def count_mu(mu, target):
    """Count how many Gaussians have the specified mean."""
    target = torch.tensor(
        target,
        dtype=mu.dtype,
        device=mu.device,
    )

    return torch.all(
        torch.isclose(mu, target),
        dim=1,
    ).sum().item()


# ---------------------------------------------------------------------
# Pruning
# ---------------------------------------------------------------------

def test_prunes_low_opacity_gaussian():
    gaussians = make_gaussians(
        mu=[
            [10, 10],
            [20, 20],
            [30, 30],
        ],
        scale=[
            [1, 1],
            [1, 1],
            [1, 1],
        ],
        opacity=[
            0.5,
            prune_opacity / 2,   # should disappear
            0.8,
        ],
    )

    # No densification.
    grad_mag = torch.zeros(3)

    out = densify(
        gaussians,
        grad_mag,
        budget=10,
        W=100,
        H=100,
    )

    mu_f = out[0]

    assert mu_f.shape[0] == 2
    assert count_mu(mu_f, [10, 10]) == 1
    assert count_mu(mu_f, [20, 20]) == 0
    assert count_mu(mu_f, [30, 30]) == 1


def test_opacity_above_threshold_survives():
    gaussians = make_gaussians(
        mu=[[10, 10]],
        scale=[[1, 1]],
        opacity=[prune_opacity * 1.01],
    )

    grad_mag = torch.zeros(1)

    out = densify(
        gaussians,
        grad_mag,
        budget=10,
        W=100,
        H=100,
    )

    assert out[0].shape[0] == 1


def test_all_gaussians_can_be_pruned():
    gaussians = make_gaussians(
        mu=[
            [10, 10],
            [20, 20],
        ],
        scale=[
            [1, 1],
            [1, 1],
        ],
        opacity=[
            prune_opacity / 2,
            prune_opacity / 2,
        ],
    )

    grad_mag = torch.tensor([
        1.0,
        1.0,
    ])

    out = densify(
        gaussians,
        grad_mag,
        budget=10,
        W=100,
        H=100,
    )

    assert out[0].shape == (0, 2)
    assert out[1].shape == (0, 2)
    assert out[2].shape == (0,)
    assert out[3].shape == (0, 3)
    assert out[4].shape == (0,)


# ---------------------------------------------------------------------
# Gradient threshold
# ---------------------------------------------------------------------

def test_gradient_below_threshold_does_not_densify():
    gaussians = make_gaussians(
        mu=[[10, 10]],
        scale=[[1, 1]],
        opacity=[0.5],
    )

    grad_mag = torch.tensor([
        grad_threshold / 2
    ])

    out = densify(
        gaussians,
        grad_mag,
        budget=10,
        W=100,
        H=100,
    )

    assert out[0].shape[0] == 1


def test_gradient_exactly_at_threshold_does_not_densify():
    """
    Implementation uses:
        grad_mag > grad_threshold

    so equality should NOT densify.
    """
    gaussians = make_gaussians(
        mu=[[10, 10]],
        scale=[[1, 1]],
        opacity=[0.5],
    )

    grad_mag = torch.tensor([
        grad_threshold
    ])

    out = densify(
        gaussians,
        grad_mag,
        budget=10,
        W=100,
        H=100,
    )

    assert out[0].shape[0] == 1


# ---------------------------------------------------------------------
# Cloning
# ---------------------------------------------------------------------

def test_small_dense_gaussian_is_cloned():
    """
    W=H=100 means:

        size threshold = .02 * 100 = 2

    scale=[1,1] is therefore small and should be cloned.
    """
    gaussians = make_gaussians(
        mu=[[25, 40]],
        scale=[[1, 1]],
        opacity=[0.5],
        color=[[0.2, 0.4, 0.6]],
        theta=[0.3],
    )

    grad_mag = torch.tensor([
        grad_threshold * 2
    ])

    out = densify(
        gaussians,
        grad_mag,
        budget=2,
        W=100,
        H=100,
    )

    mu_f, log_s_f, theta_f, color_f, op_raw_f = out

    assert mu_f.shape[0] == 2

    # Means duplicated.
    assert count_mu(mu_f, [25, 40]) == 2

    # Clone retains original scale.
    expected_scale = torch.tensor([
        [1., 1.],
        [1., 1.],
    ])

    assert torch.allclose(
        log_s_f.exp(),
        expected_scale,
    )

    # All other properties should also be duplicated.
    assert torch.allclose(theta_f[0], theta_f[1])
    assert torch.allclose(color_f[0], color_f[1])
    assert torch.allclose(op_raw_f[0], op_raw_f[1])


# ---------------------------------------------------------------------
# Splitting
# ---------------------------------------------------------------------

def test_large_dense_gaussian_is_split():
    """
    size threshold = 2.

    scale=[4,4] is large.

    Each child should therefore have:

        scale = 4 / 1.6 = 2.5
    """
    gaussians = make_gaussians(
        mu=[[25, 40]],
        scale=[[4, 4]],
        opacity=[0.5],
        color=[[0.2, 0.4, 0.6]],
        theta=[0.3],
    )

    grad_mag = torch.tensor([
        grad_threshold * 2
    ])

    out = densify(
        gaussians,
        grad_mag,
        budget=2,
        W=100,
        H=100,
    )

    mu_f, log_s_f, theta_f, color_f, op_raw_f = out

    assert mu_f.shape[0] == 2

    # Assignment says split children keep the same mean.
    assert count_mu(mu_f, [25, 40]) == 2

    expected = torch.tensor([
        [4 / split_scale, 4 / split_scale],
        [4 / split_scale, 4 / split_scale],
    ])

    assert torch.allclose(
        log_s_f.exp(),
        expected,
    )

    assert torch.allclose(theta_f[0], theta_f[1])
    assert torch.allclose(color_f[0], color_f[1])
    assert torch.allclose(op_raw_f[0], op_raw_f[1])


def test_split_if_either_axis_exceeds_size_threshold():
    """
    max(scale) is used.

    scale=[1,4] should therefore split even though
    the x scale is small.
    """
    gaussians = make_gaussians(
        mu=[[10, 10]],
        scale=[[1, 4]],
        opacity=[0.5],
    )

    grad_mag = torch.tensor([
        grad_threshold * 2
    ])

    out = densify(
        gaussians,
        grad_mag,
        budget=2,
        W=100,
        H=100,
    )

    final_scale = out[1].exp()

    expected_child = torch.tensor([
        1 / split_scale,
        4 / split_scale,
    ])

    assert torch.allclose(
        final_scale[0],
        expected_child,
    )

    assert torch.allclose(
        final_scale[1],
        expected_child,
    )


def test_scale_exactly_at_threshold_is_cloned():
    """
    Code splits only when:

        max(scale) > size_threshold * max(W,H)

    Equality should therefore clone.
    """
    W = H = 100

    threshold = size_threshold * max(W, H)

    gaussians = make_gaussians(
        mu=[[10, 10]],
        scale=[[threshold, threshold]],
        opacity=[0.5],
    )

    grad_mag = torch.tensor([
        grad_threshold * 2
    ])

    out = densify(
        gaussians,
        grad_mag,
        budget=2,
        W=W,
        H=H,
    )

    expected = torch.tensor([
        [threshold, threshold],
        [threshold, threshold],
    ])

    assert torch.allclose(
        out[1].exp(),
        expected,
    )


# ---------------------------------------------------------------------
# Budget behavior
# ---------------------------------------------------------------------

def test_budget_limits_number_of_dense_gaussians():
    """
    Three Gaussians all want densification.

    N=3, budget=4 means only ONE may be selected.

    Highest gradient should win.
    """
    gaussians = make_gaussians(
        mu=[
            [10, 10],
            [20, 20],
            [30, 30],
        ],
        scale=[
            [1, 1],
            [1, 1],
            [1, 1],
        ],
        opacity=[
            0.5,
            0.5,
            0.5,
        ],
    )

    grad_mag = torch.tensor([
        3 * grad_threshold,
        10 * grad_threshold,   # winner
        5 * grad_threshold,
    ])

    out = densify(
        gaussians,
        grad_mag,
        budget=4,
        W=100,
        H=100,
    )

    mu_f = out[0]

    assert mu_f.shape[0] == 4

    assert count_mu(mu_f, [10, 10]) == 1
    assert count_mu(mu_f, [20, 20]) == 2
    assert count_mu(mu_f, [30, 30]) == 1


def test_pruning_frees_budget_before_densification():
    """
    Begin at the budget:

        N = budget = 4

    Gaussian 1 gets pruned, freeing one slot.

    The highest-gradient surviving Gaussian should
    then use that newly freed slot.
    """
    gaussians = make_gaussians(
        mu=[
            [10, 10],
            [20, 20],   # pruned
            [30, 30],   # highest surviving gradient
            [40, 40],
        ],
        scale=[
            [1, 1],
            [1, 1],
            [1, 1],
            [1, 1],
        ],
        opacity=[
            0.5,
            prune_opacity / 2,
            0.5,
            0.5,
        ],
    )

    grad_mag = torch.tensor([
        2 * grad_threshold,
        100 * grad_threshold,
        10 * grad_threshold,
        5 * grad_threshold,
    ])

    out = densify(
        gaussians,
        grad_mag,
        budget=4,
        W=100,
        H=100,
    )

    mu_f = out[0]

    assert mu_f.shape[0] == 4

    # Pruned Gaussian is gone despite enormous gradient.
    assert count_mu(mu_f, [20, 20]) == 0

    # Highest-gradient survivor gets cloned.
    assert count_mu(mu_f, [30, 30]) == 2


def test_no_densification_when_already_at_budget():
    gaussians = make_gaussians(
        mu=[
            [10, 10],
            [20, 20],
        ],
        scale=[
            [1, 1],
            [1, 1],
        ],
        opacity=[
            0.5,
            0.5,
        ],
    )

    # Both strongly request densification.
    grad_mag = torch.tensor([
        100 * grad_threshold,
        200 * grad_threshold,
    ])

    out = densify(
        gaussians,
        grad_mag,
        budget=2,
        W=100,
        H=100,
    )

    assert out[0].shape[0] == 2

    assert count_mu(out[0], [10, 10]) == 1
    assert count_mu(out[0], [20, 20]) == 1


def test_output_never_exceeds_budget():
    N = 10

    gaussians = make_gaussians(
        mu=[[i, i] for i in range(N)],
        scale=[[1, 1]] * N,
        opacity=[0.5] * N,
    )

    # Every Gaussian qualifies.
    grad_mag = torch.arange(
        1,
        N + 1,
        dtype=torch.float32,
    ) * grad_threshold * 2

    budget = 13

    out = densify(
        gaussians,
        grad_mag,
        budget=budget,
        W=100,
        H=100,
    )

    assert out[0].shape[0] == budget

    for tensor in out:
        assert tensor.shape[0] == budget


# ---------------------------------------------------------------------
# Mixed clone / split
# ---------------------------------------------------------------------

def test_clone_and_split_in_same_densification():
    """
    Gaussian 0 is small -> clone.
    Gaussian 1 is large -> split.

    Both qualify for densification.
    """
    gaussians = make_gaussians(
        mu=[
            [10, 10],
            [20, 20],
        ],
        scale=[
            [1, 1],   # clone
            [4, 4],   # split
        ],
        opacity=[
            0.5,
            0.5,
        ],
    )

    grad_mag = torch.tensor([
        2 * grad_threshold,
        3 * grad_threshold,
    ])

    out = densify(
        gaussians,
        grad_mag,
        budget=4,
        W=100,
        H=100,
    )

    mu_f, log_s_f, _, _, _ = out

    assert mu_f.shape[0] == 4

    # Both became two children/copies.
    assert count_mu(mu_f, [10, 10]) == 2
    assert count_mu(mu_f, [20, 20]) == 2

    scales = log_s_f.exp()

    small_rows = torch.all(
        torch.isclose(
            mu_f,
            torch.tensor([10., 10.])
        ),
        dim=1,
    )

    large_rows = torch.all(
        torch.isclose(
            mu_f,
            torch.tensor([20., 20.])
        ),
        dim=1,
    )

    assert torch.allclose(
        scales[small_rows],
        torch.tensor([
            [1., 1.],
            [1., 1.],
        ])
    )

    assert torch.allclose(
        scales[large_rows],
        torch.tensor([
            [4 / split_scale, 4 / split_scale],
            [4 / split_scale, 4 / split_scale],
        ])
    )


# ---------------------------------------------------------------------
# Integrity
# ---------------------------------------------------------------------

def test_all_output_tensors_have_same_number_of_gaussians():
    gaussians = make_gaussians(
        mu=[
            [10, 10],
            [20, 20],
            [30, 30],
        ],
        scale=[
            [1, 1],
            [4, 4],
            [1, 1],
        ],
        opacity=[
            0.5,
            0.5,
            prune_opacity / 2,
        ],
    )

    grad_mag = torch.tensor([
        5 * grad_threshold,
        10 * grad_threshold,
        20 * grad_threshold,
    ])

    out = densify(
        gaussians,
        grad_mag,
        budget=5,
        W=100,
        H=100,
    )

    final_N = out[0].shape[0]

    assert all(
        tensor.shape[0] == final_N
        for tensor in out
    )


def test_densify_does_not_modify_input_tensors():
    """
    Especially important because split performs:

        s_d[mask_split] /= split_scale

    We want to ensure this does not alter the caller's
    original log_s tensor.
    """
    gaussians = make_gaussians(
        mu=[
            [10, 10],
            [20, 20],
        ],
        scale=[
            [4, 4],
            [1, 1],
        ],
        opacity=[
            0.5,
            0.5,
        ],
    )

    originals = [
        tensor.clone()
        for tensor in gaussians
    ]

    grad_mag = torch.tensor([
        10 * grad_threshold,
        5 * grad_threshold,
    ])

    densify(
        gaussians,
        grad_mag,
        budget=4,
        W=100,
        H=100,
    )

    for original, current in zip(
        originals,
        gaussians,
    ):
        assert torch.allclose(
            original,
            current,
        )