# Test cases generated by ChatGPT

import math

import pytest
import torch

from gaussian import covariance_2d, gaussian_weight
from rasterize import pixel_grid, render


# ============================================================
# pixel_grid tests
# ============================================================

def test_pixel_grid_single_pixel():
    xy = pixel_grid(1, 1)

    expected = torch.tensor([
        [0.5, 0.5]
    ], dtype=torch.float32)

    assert xy.shape == (1, 2)
    assert xy.dtype == torch.float32
    assert torch.allclose(xy, expected)


def test_pixel_grid_multiple_pixels():
    """
    Assumes coordinates are (x, y) = (column, row)
    and pixels are flattened row-major.
    """
    xy = pixel_grid(2, 3)

    expected = torch.tensor([
        [0.5, 0.5],
        [1.5, 0.5],
        [2.5, 0.5],
        [0.5, 1.5],
        [1.5, 1.5],
        [2.5, 1.5],
    ], dtype=torch.float32)

    assert xy.shape == (6, 2)
    assert torch.allclose(xy, expected)


# ============================================================
# Basic render tests
# ============================================================

def test_render_output_shape():
    H, W = 3, 4
    N = 2

    mu = torch.tensor([
        [0.5, 0.5],
        [2.5, 1.5],
    ], dtype=torch.float32)

    scale = torch.ones((N, 2), dtype=torch.float32)
    theta = torch.zeros(N, dtype=torch.float32)

    Sigma = covariance_2d(scale, theta)

    color = torch.tensor([
        [1.0, 0.0, 0.0],
        [0.0, 0.0, 1.0],
    ], dtype=torch.float32)

    opacity = torch.tensor([0.5, 0.5], dtype=torch.float32)

    image = render(
        mu,
        Sigma,
        color,
        opacity,
        torch.arange(N),
        H,
        W,
    )

    assert image.shape == (H, W, 3)
    assert image.dtype == torch.float32
    assert torch.isfinite(image).all()


def test_single_gaussian_at_center_full_opacity():
    """
    One pixel centered at (0.5, 0.5).
    Gaussian is also centered there.

    G(mu) = 1
    opacity = 1

    Therefore:
        C = color
    """
    H = W = 1

    mu = torch.tensor([
        [0.5, 0.5]
    ], dtype=torch.float32)

    Sigma = covariance_2d(
        torch.tensor([[1.0, 1.0]], dtype=torch.float32),
        torch.tensor([0.0], dtype=torch.float32),
    )

    color = torch.tensor([
        [0.2, 0.6, 0.9]
    ], dtype=torch.float32)

    opacity = torch.tensor([1.0], dtype=torch.float32)

    image = render(
        mu, Sigma, color, opacity,
        torch.arange(1), H, W
    )

    expected = torch.tensor([
        [[0.2, 0.6, 0.9]]
    ], dtype=torch.float32)

    assert torch.allclose(image, expected, atol=1e-6)


def test_single_gaussian_partial_opacity():
    """
    At Gaussian center:
        G = 1
        alpha = opacity = 0.25

    Premultiplied contribution:
        C = alpha * color
    """
    H = W = 1

    mu = torch.tensor([
        [0.5, 0.5]
    ], dtype=torch.float32)

    Sigma = covariance_2d(
        torch.tensor([[1.0, 1.0]], dtype=torch.float32),
        torch.tensor([0.0], dtype=torch.float32),
    )

    color = torch.tensor([
        [0.8, 0.4, 0.2]
    ], dtype=torch.float32)

    opacity = torch.tensor([0.25], dtype=torch.float32)

    image = render(
        mu, Sigma, color, opacity,
        torch.arange(1), H, W
    )

    expected = torch.tensor([
        [[0.20, 0.10, 0.05]]
    ], dtype=torch.float32)

    assert torch.allclose(image, expected, atol=1e-6)


def test_zero_opacity_contributes_nothing():
    H = W = 1

    mu = torch.tensor([
        [0.5, 0.5]
    ], dtype=torch.float32)

    Sigma = covariance_2d(
        torch.tensor([[1.0, 1.0]], dtype=torch.float32),
        torch.tensor([0.0], dtype=torch.float32),
    )

    color = torch.tensor([
        [1.0, 0.5, 0.25]
    ], dtype=torch.float32)

    opacity = torch.tensor([0.0], dtype=torch.float32)

    image = render(
        mu, Sigma, color, opacity,
        torch.arange(1), H, W
    )

    assert torch.allclose(
        image,
        torch.zeros((1, 1, 3), dtype=torch.float32),
        atol=1e-6,
    )


# ============================================================
# Gaussian spatial falloff
# ============================================================

def test_single_gaussian_spatial_falloff():
    """
    1x2 image:

        pixel 0 center = (0.5, 0.5)
        pixel 1 center = (1.5, 0.5)

    Gaussian:
        mu = (0.5, 0.5)
        Sigma = I

    Therefore:

        G(pixel 0) = 1
        G(pixel 1) = exp(-1/2)

    With opacity=1 and red color, the red channel should
    equal these Gaussian weights.
    """
    H, W = 1, 2

    mu = torch.tensor([
        [0.5, 0.5]
    ], dtype=torch.float32)

    Sigma = covariance_2d(
        torch.tensor([[1.0, 1.0]], dtype=torch.float32),
        torch.tensor([0.0], dtype=torch.float32),
    )

    color = torch.tensor([
        [1.0, 0.0, 0.0]
    ], dtype=torch.float32)

    opacity = torch.tensor([1.0], dtype=torch.float32)

    image = render(
        mu, Sigma, color, opacity,
        torch.arange(1), H, W
    )

    expected = torch.tensor([
        [
            [1.0, 0.0, 0.0],
            [math.exp(-0.5), 0.0, 0.0],
        ]
    ], dtype=torch.float32)

    assert torch.allclose(image, expected, atol=1e-6)


# ============================================================
# Alpha blending / transmittance
# ============================================================

def test_two_gaussians_front_to_back():
    """
    Both Gaussians lie at the only pixel center, so G=1 for both.

    Front:
        red
        alpha = 0.5

    Back:
        blue
        alpha = 0.5

    C =
        1 * 0.5 * red
        +
        (1 - 0.5) * 0.5 * blue

      = [0.5, 0, 0.25]
    """
    H = W = 1
    N = 2

    mu = torch.tensor([
        [0.5, 0.5],
        [0.5, 0.5],
    ], dtype=torch.float32)

    Sigma = covariance_2d(
        torch.ones((N, 2), dtype=torch.float32),
        torch.zeros(N, dtype=torch.float32),
    )

    color = torch.tensor([
        [1.0, 0.0, 0.0],  # red
        [0.0, 0.0, 1.0],  # blue
    ], dtype=torch.float32)

    opacity = torch.tensor([
        0.5,
        0.5,
    ], dtype=torch.float32)

    order = torch.tensor([0, 1])

    image = render(
        mu, Sigma, color, opacity,
        order, H, W
    )

    expected = torch.tensor([
        [[0.5, 0.0, 0.25]]
    ], dtype=torch.float32)

    assert torch.allclose(image, expected, atol=1e-6)


def test_reversing_order_changes_result():
    """
    Same Gaussians as previous test, but blue is now in front.

    C =
        0.5 * blue
        +
        0.5 * 0.5 * red

      = [0.25, 0, 0.5]
    """
    H = W = 1
    N = 2

    mu = torch.tensor([
        [0.5, 0.5],
        [0.5, 0.5],
    ], dtype=torch.float32)

    Sigma = covariance_2d(
        torch.ones((N, 2), dtype=torch.float32),
        torch.zeros(N, dtype=torch.float32),
    )

    color = torch.tensor([
        [1.0, 0.0, 0.0],
        [0.0, 0.0, 1.0],
    ], dtype=torch.float32)

    opacity = torch.tensor([
        0.5,
        0.5,
    ], dtype=torch.float32)

    order = torch.tensor([1, 0])

    image = render(
        mu, Sigma, color, opacity,
        order, H, W
    )

    expected = torch.tensor([
        [[0.25, 0.0, 0.5]]
    ], dtype=torch.float32)

    assert torch.allclose(image, expected, atol=1e-6)


def test_three_gaussians_transmittance():
    """
    Three Gaussians all centered at the only pixel.

    Therefore Gaussian weights are all 1.

    alpha:
        a0 = 0.2
        a1 = 0.5
        a2 = 0.25

    Transmittance:
        T0 = 1
        T1 = 0.8
        T2 = 0.8 * 0.5 = 0.4

    Colors:
        Gaussian 0 = red
        Gaussian 1 = green
        Gaussian 2 = blue

    Contributions:
        red   = 1.0 * 0.2       = 0.2
        green = 0.8 * 0.5       = 0.4
        blue  = 0.4 * 0.25      = 0.1

    Final:
        [0.2, 0.4, 0.1]
    """
    H = W = 1
    N = 3

    mu = torch.tensor([
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
    ], dtype=torch.float32)

    Sigma = covariance_2d(
        torch.ones((N, 2), dtype=torch.float32),
        torch.zeros(N, dtype=torch.float32),
    )

    color = torch.tensor([
        [1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0],
        [0.0, 0.0, 1.0],
    ], dtype=torch.float32)

    opacity = torch.tensor([
        0.2,
        0.5,
        0.25,
    ], dtype=torch.float32)

    image = render(
        mu, Sigma, color, opacity,
        torch.arange(N), H, W
    )

    expected = torch.tensor([
        [[0.2, 0.4, 0.1]]
    ], dtype=torch.float32)

    assert torch.allclose(image, expected, atol=1e-6)


def test_fully_opaque_front_gaussian_blocks_back():
    """
    If the front Gaussian has alpha=1 at this pixel:

        T_after_front = 1 - 1 = 0

    so nothing behind it contributes.
    """
    H = W = 1
    N = 2

    mu = torch.tensor([
        [0.5, 0.5],
        [0.5, 0.5],
    ], dtype=torch.float32)

    Sigma = covariance_2d(
        torch.ones((N, 2), dtype=torch.float32),
        torch.zeros(N, dtype=torch.float32),
    )

    color = torch.tensor([
        [1.0, 0.0, 0.0],  # red front
        [0.0, 0.0, 1.0],  # blue back
    ], dtype=torch.float32)

    opacity = torch.tensor([
        1.0,
        1.0,
    ], dtype=torch.float32)

    image = render(
        mu, Sigma, color, opacity,
        torch.tensor([0, 1]), H, W
    )

    expected = torch.tensor([
        [[1.0, 0.0, 0.0]]
    ], dtype=torch.float32)

    assert torch.allclose(image, expected, atol=1e-6)


# ============================================================
# Reference implementation comparison
# ============================================================

def test_render_matches_reference_implementation():
    """
    This is one of the strongest tests.

    We independently calculate the expected result using
    gaussian_weight and a simple explicit front-to-back loop.
    """
    H, W = 2, 2
    N = 3

    mu = torch.tensor([
        [0.4, 0.7],
        [1.3, 0.6],
        [1.0, 1.5],
    ], dtype=torch.float32)

    scale = torch.tensor([
        [0.8, 1.1],
        [1.3, 0.7],
        [0.9, 1.4],
    ], dtype=torch.float32)

    theta = torch.tensor([
        0.2,
        -0.5,
        0.8,
    ], dtype=torch.float32)

    Sigma = covariance_2d(scale, theta)

    color = torch.tensor([
        [0.9, 0.1, 0.2],
        [0.2, 0.8, 0.3],
        [0.1, 0.3, 0.9],
    ], dtype=torch.float32)

    opacity = torch.tensor([
        0.6,
        0.4,
        0.7,
    ], dtype=torch.float32)

    # Deliberately nontrivial ordering
    order = torch.tensor([2, 0, 1])

    actual = render(
        mu, Sigma, color, opacity,
        order, H, W
    )

    # ----- Independent reference calculation -----

    xy = pixel_grid(H, W)

    weights = gaussian_weight(
        xy, mu, Sigma
    )  # (P, N)

    alpha = weights * opacity[None, :]

    expected_flat = torch.zeros(
        (H * W, 3),
        dtype=torch.float32
    )

    transmittance = torch.ones(
        H * W,
        dtype=torch.float32
    )

    for i in order:
        a = alpha[:, i]

        expected_flat = (
            expected_flat
            + transmittance[:, None]
            * a[:, None]
            * color[i]
        )

        transmittance = (
            transmittance * (1.0 - a)
        )

    expected = expected_flat.reshape(H, W, 3)

    assert torch.allclose(
        actual,
        expected,
        atol=1e-5
    )


# ============================================================
# Autograd test
# ============================================================

def test_render_preserves_gradients():
    """
    Make sure gradients propagate through the entire pipeline:

      mu ----------------------\
      scale -> Sigma ---------- \
      theta -> Sigma ----------- > Gaussian weights
      opacity ----------------- /          |
      color ------------------/            v
                                      alpha blending
                                           |
                                           v
                                         image
                                           |
                                           v
                                          loss

    We want gradients for:
        mu
        scale
        theta
        color
        opacity
    """
    H, W = 2, 2
    N = 2

    mu = torch.tensor([
        [0.7, 0.8],
        [1.4, 1.1],
    ], dtype=torch.float32, requires_grad=True)

    scale = torch.tensor([
        [0.9, 1.2],
        [1.4, 0.7],
    ], dtype=torch.float32, requires_grad=True)

    theta = torch.tensor([
        0.31,
        -0.57,
    ], dtype=torch.float32, requires_grad=True)

    Sigma = covariance_2d(
        scale,
        theta
    )

    color = torch.tensor([
        [0.8, 0.2, 0.1],
        [0.1, 0.4, 0.9],
    ], dtype=torch.float32, requires_grad=True)

    opacity = torch.tensor([
        0.6,
        0.35,
    ], dtype=torch.float32, requires_grad=True)

    image = render(
        mu,
        Sigma,
        color,
        opacity,
        torch.arange(N),
        H,
        W,
    )

    # Nonuniform coefficients reduce the chance that symmetry
    # accidentally makes a legitimate gradient zero.
    coefficients = torch.tensor([
        [
            [1.0, 0.7, 1.3],
            [0.4, 1.8, 0.6],
        ],
        [
            [1.5, 0.2, 0.9],
            [0.8, 1.1, 2.0],
        ],
    ], dtype=torch.float32)

    loss = (image * coefficients).sum()

    loss.backward()

    assert mu.grad is not None
    assert scale.grad is not None
    assert theta.grad is not None
    assert color.grad is not None
    assert opacity.grad is not None

    assert torch.isfinite(mu.grad).all()
    assert torch.isfinite(scale.grad).all()
    assert torch.isfinite(theta.grad).all()
    assert torch.isfinite(color.grad).all()
    assert torch.isfinite(opacity.grad).all()


# ============================================================
# Various sizes
# ============================================================

@pytest.mark.parametrize(
    "H,W,N",
    [
        (1, 1, 1),
        (1, 5, 2),
        (4, 1, 3),
        (3, 4, 5),
    ]
)
def test_render_various_sizes(H, W, N):
    mu = torch.rand(N, 2, dtype=torch.float32)

    mu[:, 0] *= W
    mu[:, 1] *= H

    scale = (
        torch.rand(N, 2, dtype=torch.float32)
        + 0.3
    )

    theta = torch.randn(
        N,
        dtype=torch.float32
    )

    Sigma = covariance_2d(
        scale,
        theta
    )

    color = torch.rand(
        N, 3,
        dtype=torch.float32
    )

    opacity = torch.rand(
        N,
        dtype=torch.float32
    )

    image = render(
        mu,
        Sigma,
        color,
        opacity,
        torch.arange(N),
        H,
        W,
    )

    assert image.shape == (H, W, 3)
    assert image.dtype == torch.float32
    assert torch.isfinite(image).all()