# Tests generated by ChatGPT

import torch
import pytest

from gaussian_3d import quaternion_to_rotation, covariance_3d, project_gaussian

def test_output_shape():
    """(N, 4) quaternions should produce (N, 3, 3) matrices."""
    q = torch.randn(10, 4)

    R = quaternion_to_rotation(q)

    assert R.shape == (10, 3, 3)


def test_identity_quaternion():
    """q = (1, 0, 0, 0) should give the identity rotation."""
    q = torch.tensor([
        [1.0, 0.0, 0.0, 0.0]
    ])

    R = quaternion_to_rotation(q)

    expected = torch.eye(3).unsqueeze(0)

    assert torch.allclose(R, expected, atol=1e-6)


def test_unnormalized_identity_quaternion():
    """
    Quaternion magnitude should not matter because the function
    normalizes q internally.
    """
    q = torch.tensor([
        [5.0, 0.0, 0.0, 0.0]
    ])

    R = quaternion_to_rotation(q)

    expected = torch.eye(3).unsqueeze(0)

    assert torch.allclose(R, expected, atol=1e-6)


def test_normalization_invariance():
    """
    q and k*q should represent the same rotation for positive k.
    """
    q = torch.tensor([
        [1.0, 2.0, 3.0, 4.0],
        [2.0, -1.0, 0.5, 3.0]
    ])

    R1 = quaternion_to_rotation(q)
    R2 = quaternion_to_rotation(7.0 * q)

    assert torch.allclose(R1, R2, atol=1e-5)


def test_known_180_degree_x_rotation():
    """
    q = (0, 1, 0, 0) represents a 180-degree rotation around x.

    Expected:
        x ->  x
        y -> -y
        z -> -z
    """
    q = torch.tensor([
        [0.0, 1.0, 0.0, 0.0]
    ])

    R = quaternion_to_rotation(q)

    expected = torch.tensor([[
        [1.0,  0.0,  0.0],
        [0.0, -1.0,  0.0],
        [0.0,  0.0, -1.0]
    ]])

    assert torch.allclose(R, expected, atol=1e-6)


def test_rotation_matrix_is_orthogonal():
    """
    A valid rotation matrix must satisfy:

        R R^T = I
    """
    q = torch.randn(20, 4)

    R = quaternion_to_rotation(q)

    product = R @ R.mT

    expected = (
        torch.eye(3, dtype=R.dtype, device=R.device)
        .unsqueeze(0)
        .expand(20, -1, -1)
    )

    assert torch.allclose(product, expected, atol=1e-5)


def test_rotation_matrix_determinant():
    """A proper 3D rotation matrix should have determinant +1."""
    q = torch.randn(20, 4)

    R = quaternion_to_rotation(q)

    det = torch.linalg.det(R)

    expected = torch.ones_like(det)

    assert torch.allclose(det, expected, atol=1e-5)


def test_batch_independence():
    """
    Batched evaluation should give the same answer as evaluating
    each quaternion separately.
    """
    q = torch.randn(8, 4)

    R_batch = quaternion_to_rotation(q)

    for i in range(q.shape[0]):
        R_single = quaternion_to_rotation(q[i:i+1])

        assert torch.allclose(
            R_batch[i:i+1],
            R_single,
            atol=1e-6
        )


def test_preserves_dtype():
    """Output should retain q's floating-point dtype."""
    q = torch.randn(5, 4, dtype=torch.float64)

    R = quaternion_to_rotation(q)

    assert R.dtype == q.dtype


def test_preserves_device():
    """Output must remain on the same device as q."""
    device = (
        torch.device("mps")
        if torch.backends.mps.is_available()
        else torch.device("cpu")
    )

    q = torch.randn(5, 4, device=device)

    R = quaternion_to_rotation(q)

    assert R.device == q.device


def test_gradient_propagation():
    """
    quaternion_to_rotation must preserve the autograd graph.
    """
    q = torch.randn(
        5, 4,
        requires_grad=True
    )

    R = quaternion_to_rotation(q)

    assert R.requires_grad
    assert R.grad_fn is not None

    # Don't use R.sum() here: because of rotation-matrix symmetry,
    # that particular loss can accidentally produce zero gradients
    # for some quaternions.
    weights = torch.arange(
        1,
        R.numel() + 1,
        dtype=R.dtype,
        device=R.device
    ).reshape_as(R)

    loss = (R * weights).sum()
    loss.backward()

    assert q.grad is not None
    assert q.grad.shape == q.shape
    assert torch.isfinite(q.grad).all()

# ============================================================
# covariance_3d tests
# ============================================================

def test_covariance_3d_output_shape():
    """(N, 3) scales + (N, 4) quaternions -> (N, 3, 3)."""
    scale = torch.rand(10, 3) + 0.1
    quat = torch.randn(10, 4)

    Sigma = covariance_3d(scale, quat)

    assert Sigma.shape == (10, 3, 3)


def test_covariance_3d_identity_rotation():
    """
    With identity quaternion q=(1,0,0,0),
    Sigma should simply be diag(scale^2).
    """
    scale = torch.tensor([
        [1.0, 2.0, 3.0],
        [4.0, 5.0, 6.0]
    ])

    quat = torch.tensor([
        [1.0, 0.0, 0.0, 0.0],
        [1.0, 0.0, 0.0, 0.0]
    ])

    Sigma = covariance_3d(scale, quat)

    expected = torch.diag_embed(scale.square())

    assert torch.allclose(Sigma, expected, atol=1e-6)


def test_covariance_3d_isotropic_rotation_invariant():
    """
    If sx=sy=sz, rotating the Gaussian should not change
    the covariance matrix.

    Sigma should equal s^2 I for ANY rotation.
    """
    scale = torch.tensor([
        [2.0, 2.0, 2.0],
        [3.5, 3.5, 3.5]
    ])

    quat = torch.randn(2, 4)

    Sigma = covariance_3d(scale, quat)

    expected = torch.stack([
        4.0 * torch.eye(3),
        12.25 * torch.eye(3)
    ])

    assert torch.allclose(Sigma, expected, atol=1e-5)


def test_covariance_3d_symmetric():
    """Every covariance matrix must satisfy Sigma = Sigma^T."""
    scale = torch.rand(20, 3) * 5.0 + 0.1
    quat = torch.randn(20, 4)

    Sigma = covariance_3d(scale, quat)

    assert torch.allclose(
        Sigma,
        Sigma.mT,
        atol=1e-5
    )


def test_covariance_3d_positive_definite():
    """
    Positive scales should produce a positive-definite covariance.

    Therefore every eigenvalue should be > 0.
    """
    scale = torch.rand(20, 3) * 5.0 + 0.5
    quat = torch.randn(20, 4)

    Sigma = covariance_3d(scale, quat)

    eigenvalues = torch.linalg.eigvalsh(Sigma)

    assert torch.all(eigenvalues > 0)


def test_covariance_3d_eigenvalues_are_squared_scales():
    """
    Rotation changes the covariance's orientation but not its
    eigenvalues.

    Eigenvalues(Sigma) = {sx^2, sy^2, sz^2}.
    """
    scale = torch.rand(20, 3) * 4.0 + 0.5
    quat = torch.randn(20, 4)

    Sigma = covariance_3d(scale, quat)

    actual = torch.linalg.eigvalsh(Sigma)

    # eigvalsh returns eigenvalues in ascending order
    expected = torch.sort(scale.square(), dim=-1).values

    assert torch.allclose(actual, expected, atol=1e-4)


def test_covariance_3d_quaternion_magnitude_invariant():
    """
    Since quaternion_to_rotation normalizes q internally,
    multiplying q by a positive scalar should not change Sigma.
    """
    scale = torch.rand(10, 3) + 0.5
    quat = torch.randn(10, 4)

    Sigma1 = covariance_3d(scale, quat)
    Sigma2 = covariance_3d(scale, 7.0 * quat)

    assert torch.allclose(Sigma1, Sigma2, atol=1e-5)


def test_covariance_3d_batch_independence():
    """
    Computing a batch should give the same result as computing
    each Gaussian independently.
    """
    scale = torch.rand(8, 3) + 0.5
    quat = torch.randn(8, 4)

    Sigma_batch = covariance_3d(scale, quat)

    for i in range(8):
        Sigma_single = covariance_3d(
            scale[i:i+1],
            quat[i:i+1]
        )

        assert torch.allclose(
            Sigma_batch[i:i+1],
            Sigma_single,
            atol=1e-6
        )


def test_covariance_3d_preserves_dtype():
    """Output should have the same floating-point dtype."""
    scale = torch.rand(5, 3, dtype=torch.float64) + 0.5
    quat = torch.randn(5, 4, dtype=torch.float64)

    Sigma = covariance_3d(scale, quat)

    assert Sigma.dtype == scale.dtype


def test_covariance_3d_preserves_device():
    """Output should remain on the same device as the inputs."""
    device = (
        torch.device("mps")
        if torch.backends.mps.is_available()
        else torch.device("cpu")
    )

    scale = torch.rand(5, 3, device=device) + 0.5
    quat = torch.randn(5, 4, device=device)

    Sigma = covariance_3d(scale, quat)

    assert Sigma.device == scale.device
    assert Sigma.device == quat.device


def test_covariance_3d_gradient_propagation():
    """
    Gradients must propagate through both scale and quaternion.
    """
    scale = (
        torch.rand(5, 3) + 0.5
    ).requires_grad_()

    quat = torch.randn(
        5, 4,
        requires_grad=True
    )

    Sigma = covariance_3d(scale, quat)

    assert Sigma.requires_grad
    assert Sigma.grad_fn is not None

    # Use nonuniform weights so the loss depends on orientation too.
    weights = torch.arange(
        1,
        Sigma.numel() + 1,
        dtype=Sigma.dtype,
        device=Sigma.device
    ).reshape_as(Sigma)

    loss = (Sigma * weights).sum()
    loss.backward()

    assert scale.grad is not None
    assert quat.grad is not None

    assert scale.grad.shape == scale.shape
    assert quat.grad.shape == quat.shape

    assert torch.isfinite(scale.grad).all()
    assert torch.isfinite(quat.grad).all()

# ============================================================
# project_gaussian tests
# ============================================================

def test_project_gaussian_output_shapes():
    N = 10

    mu3 = torch.randn(N, 3)
    mu3[:, 2] += 5.0

    Sigma3 = torch.eye(3).unsqueeze(0).repeat(N, 1, 1)

    R_wc = torch.eye(3)
    t = torch.zeros(3)

    K = torch.tensor([
        [100.0,   0.0, 50.0],
        [  0.0, 100.0, 50.0],
        [  0.0,   0.0,  1.0]
    ])

    mu2, Sigma2, depth = project_gaussian(
        mu3, Sigma3, R_wc, t, K
    )

    assert mu2.shape == (N, 2)
    assert Sigma2.shape == (N, 2, 2)
    assert depth.shape == (N,)


def test_project_gaussian_center_point():
    """
    A point on the camera's optical axis should project
    to the principal point (cx, cy).
    """
    mu3 = torch.tensor([
        [0.0, 0.0, 5.0]
    ])

    Sigma3 = torch.eye(3).unsqueeze(0)

    R_wc = torch.eye(3)
    t = torch.zeros(3)

    K = torch.tensor([
        [100.0,   0.0, 40.0],
        [  0.0, 200.0, 30.0],
        [  0.0,   0.0,  1.0]
    ])

    mu2, _, depth = project_gaussian(
        mu3, Sigma3, R_wc, t, K
    )

    expected_mu = torch.tensor([
        [40.0, 30.0]
    ])

    assert torch.allclose(mu2, expected_mu, atol=1e-6)
    assert torch.allclose(depth, torch.tensor([5.0]), atol=1e-6)


def test_project_gaussian_known_projection():
    """
    Explicitly test:
        u = fx*x/z + cx
        v = fy*y/z + cy
    """
    mu3 = torch.tensor([
        [2.0, 3.0, 4.0]
    ])

    Sigma3 = torch.eye(3).unsqueeze(0)

    R_wc = torch.eye(3)
    t = torch.zeros(3)

    K = torch.tensor([
        [100.0,   0.0, 10.0],
        [  0.0, 200.0, 20.0],
        [  0.0,   0.0,  1.0]
    ])

    mu2, _, depth = project_gaussian(
        mu3, Sigma3, R_wc, t, K
    )

    # u = 100 * 2/4 + 10 = 60
    # v = 200 * 3/4 + 20 = 170
    expected_mu = torch.tensor([
        [60.0, 170.0]
    ])

    assert torch.allclose(mu2, expected_mu, atol=1e-6)
    assert torch.allclose(depth, torch.tensor([4.0]), atol=1e-6)


def test_project_gaussian_translation():
    """
    Check that camera translation is applied before projection.

    world point = (0,0,5)
    t           = (2,0,0)

    camera point = (2,0,5)
    """
    mu3 = torch.tensor([
        [0.0, 0.0, 5.0]
    ])

    Sigma3 = torch.eye(3).unsqueeze(0)

    R_wc = torch.eye(3)

    t = torch.tensor([2.0, 0.0, 0.0])

    K = torch.tensor([
        [100.0,   0.0, 0.0],
        [  0.0, 100.0, 0.0],
        [  0.0,   0.0, 1.0]
    ])

    mu2, _, depth = project_gaussian(
        mu3, Sigma3, R_wc, t, K
    )

    # u = 100 * 2/5 = 40
    # v = 0
    expected = torch.tensor([
        [40.0, 0.0]
    ])

    assert torch.allclose(mu2, expected, atol=1e-6)
    assert torch.allclose(depth, torch.tensor([5.0]), atol=1e-6)


def test_project_gaussian_known_covariance_on_axis():
    """
    For mu=(0,0,z), the projection Jacobian is

        [[fx/z,    0, 0],
         [   0, fy/z, 0]]

    Therefore an identity 3D covariance should project to

        [[(fx/z)^2,       0],
         [      0, (fy/z)^2]]
    """
    mu3 = torch.tensor([
        [0.0, 0.0, 5.0]
    ])

    Sigma3 = torch.eye(3).unsqueeze(0)

    R_wc = torch.eye(3)
    t = torch.zeros(3)

    K = torch.tensor([
        [100.0,   0.0, 0.0],
        [  0.0, 200.0, 0.0],
        [  0.0,   0.0, 1.0]
    ])

    _, Sigma2, _ = project_gaussian(
        mu3, Sigma3, R_wc, t, K
    )

    # (100/5)^2 = 400
    # (200/5)^2 = 1600
    expected = torch.tensor([[
        [400.0,    0.0],
        [  0.0, 1600.0]
    ]])

    assert torch.allclose(Sigma2, expected, atol=1e-5)


def test_project_gaussian_covariance_scales_with_depth():
    """
    Moving an otherwise identical Gaussian twice as far away
    should reduce its projected covariance by 1/4.

    J scales as 1/z, so Sigma2 = J Sigma J^T scales as 1/z^2.
    """
    Sigma3 = torch.eye(3).unsqueeze(0)

    R_wc = torch.eye(3)
    t = torch.zeros(3)

    K = torch.tensor([
        [100.0,   0.0, 0.0],
        [  0.0, 100.0, 0.0],
        [  0.0,   0.0, 1.0]
    ])

    near = torch.tensor([
        [0.0, 0.0, 5.0]
    ])

    far = torch.tensor([
        [0.0, 0.0, 10.0]
    ])

    _, Sigma_near, _ = project_gaussian(
        near, Sigma3, R_wc, t, K
    )

    _, Sigma_far, _ = project_gaussian(
        far, Sigma3, R_wc, t, K
    )

    assert torch.allclose(
        Sigma_far,
        Sigma_near / 4.0,
        atol=1e-5
    )


def test_project_gaussian_covariance_symmetric():
    """Projected covariance should remain symmetric."""
    N = 20

    mu3 = torch.randn(N, 3)
    mu3[:, 2] += 10.0

    A = torch.randn(N, 3, 3)
    Sigma3 = A @ A.mT + 0.1 * torch.eye(3)

    R_wc = torch.eye(3)
    t = torch.zeros(3)

    K = torch.tensor([
        [100.0,   0.0, 50.0],
        [  0.0, 100.0, 50.0],
        [  0.0,   0.0, 1.0]
    ])

    _, Sigma2, _ = project_gaussian(
        mu3, Sigma3, R_wc, t, K
    )

    assert torch.allclose(
        Sigma2,
        Sigma2.mT,
        atol=1e-5
    )


def test_project_gaussian_covariance_positive_semidefinite():
    """
    J Sigma J^T should be positive semidefinite whenever
    Sigma is positive semidefinite.
    """
    N = 20

    mu3 = torch.randn(N, 3)
    mu3[:, 2] += 10.0

    A = torch.randn(N, 3, 3)
    Sigma3 = A @ A.mT + 0.1 * torch.eye(3)

    R_wc = torch.eye(3)
    t = torch.zeros(3)

    K = torch.tensor([
        [100.0,   0.0, 50.0],
        [  0.0, 100.0, 50.0],
        [  0.0,   0.0, 1.0]
    ])

    _, Sigma2, _ = project_gaussian(
        mu3, Sigma3, R_wc, t, K
    )

    eigvals = torch.linalg.eigvalsh(Sigma2)

    # Small negative values can occur from floating-point error.
    assert torch.all(eigvals >= -1e-5)


def test_project_gaussian_batch_independence():
    """Batching should not change the result."""
    N = 8

    mu3 = torch.randn(N, 3)
    mu3[:, 2] += 10.0

    A = torch.randn(N, 3, 3)
    Sigma3 = A @ A.mT + 0.1 * torch.eye(3)

    R_wc = torch.eye(3)
    t = torch.zeros(3)

    K = torch.tensor([
        [100.0,   0.0, 50.0],
        [  0.0, 100.0, 50.0],
        [  0.0,   0.0, 1.0]
    ])

    mu2_batch, Sigma2_batch, depth_batch = project_gaussian(
        mu3, Sigma3, R_wc, t, K
    )

    for i in range(N):
        mu2_single, Sigma2_single, depth_single = project_gaussian(
            mu3[i:i+1],
            Sigma3[i:i+1],
            R_wc,
            t,
            K
        )

        assert torch.allclose(
            mu2_batch[i:i+1],
            mu2_single,
            atol=1e-6
        )

        assert torch.allclose(
            Sigma2_batch[i:i+1],
            Sigma2_single,
            atol=1e-5
        )

        assert torch.allclose(
            depth_batch[i:i+1],
            depth_single,
            atol=1e-6
        )


def test_project_gaussian_preserves_device():
    device = (
        torch.device("mps")
        if torch.backends.mps.is_available()
        else torch.device("cpu")
    )

    mu3 = torch.tensor(
        [[1.0, 2.0, 5.0]],
        device=device
    )

    Sigma3 = torch.eye(
        3,
        device=device
    ).unsqueeze(0)

    R_wc = torch.eye(3, device=device)
    t = torch.zeros(3, device=device)

    K = torch.tensor([
        [100.0,   0.0, 50.0],
        [  0.0, 100.0, 50.0],
        [  0.0,   0.0, 1.0]
    ], device=device)

    mu2, Sigma2, depth = project_gaussian(
        mu3, Sigma3, R_wc, t, K
    )

    assert mu2.device.type == device.type
    assert Sigma2.device.type == device.type
    assert depth.device.type == device.type


def test_project_gaussian_preserves_dtype():
    dtype = torch.float64

    mu3 = torch.tensor(
        [[1.0, 2.0, 5.0]],
        dtype=dtype
    )

    Sigma3 = torch.eye(
        3,
        dtype=dtype
    ).unsqueeze(0)

    R_wc = torch.eye(3, dtype=dtype)
    t = torch.zeros(3, dtype=dtype)

    K = torch.tensor([
        [100.0,   0.0, 50.0],
        [  0.0, 100.0, 50.0],
        [  0.0,   0.0, 1.0]
    ], dtype=dtype)

    mu2, Sigma2, depth = project_gaussian(
        mu3, Sigma3, R_wc, t, K
    )

    assert mu2.dtype == dtype
    assert Sigma2.dtype == dtype
    assert depth.dtype == dtype


def test_project_gaussian_gradient_propagation():
    """
    Projection must preserve gradients back to both the
    3D mean and 3D covariance.
    """
    mu3 = torch.tensor(
        [[1.0, 2.0, 5.0]],
        requires_grad=True
    )

    A = torch.tensor(
        [[[1.0, 0.2, 0.1],
          [0.0, 1.5, 0.3],
          [0.0, 0.0, 0.8]]],
        requires_grad=True
    )

    # Make a valid covariance while keeping the graph.
    Sigma3 = A @ A.mT

    R_wc = torch.eye(3)
    t = torch.zeros(3)

    K = torch.tensor([
        [100.0,   0.0, 50.0],
        [  0.0, 120.0, 40.0],
        [  0.0,   0.0, 1.0]
    ])

    mu2, Sigma2, depth = project_gaussian(
        mu3, Sigma3, R_wc, t, K
    )

    loss = (
        mu2.square().sum()
        + Sigma2.square().sum()
        + depth.square().sum()
    )

    loss.backward()

    assert mu3.grad is not None
    assert A.grad is not None

    assert torch.isfinite(mu3.grad).all()
    assert torch.isfinite(A.grad).all()