# Test cases generated by ChatGPT

import math

import pytest
import torch

from gaussian import covariance_2d

def test_single_axis_aligned_gaussian():
    """theta = 0 should give diag(sx^2, sy^2)."""
    scale = torch.tensor([[2.0, 3.0]], dtype=torch.float32)
    theta = torch.tensor([0.0], dtype=torch.float32)

    cov = covariance_2d(scale, theta)

    expected = torch.tensor([
        [[4.0, 0.0],
         [0.0, 9.0]]
    ], dtype=torch.float32)

    assert cov.shape == (1, 2, 2)
    assert cov.dtype == torch.float32
    assert torch.allclose(cov, expected, atol=1e-6)


def test_90_degree_rotation():
    """
    Rotating by 90 degrees should swap the two principal variances.

    diag(4, 9) -> diag(9, 4)
    """
    scale = torch.tensor([[2.0, 3.0]], dtype=torch.float32)
    theta = torch.tensor([math.pi / 2], dtype=torch.float32)

    cov = covariance_2d(scale, theta)

    expected = torch.tensor([
        [[9.0, 0.0],
         [0.0, 4.0]]
    ], dtype=torch.float32)

    assert torch.allclose(cov, expected, atol=1e-5)


def test_45_degree_rotation():
    """
    For scale = (3, 1) and theta = pi/4:

        Sigma = R diag(9, 1) R^T
              = [[5, 4],
                 [4, 5]]

    assuming the standard counterclockwise rotation convention.
    """
    scale = torch.tensor([[3.0, 1.0]], dtype=torch.float32)
    theta = torch.tensor([math.pi / 4], dtype=torch.float32)

    cov = covariance_2d(scale, theta)

    expected = torch.tensor([
        [[5.0, 4.0],
         [4.0, 5.0]]
    ], dtype=torch.float32)

    assert torch.allclose(cov, expected, atol=1e-5)


def test_batch():
    """The function should handle N Gaussians independently."""
    scale = torch.tensor([
        [2.0, 3.0],
        [1.0, 4.0],
        [5.0, 2.0],
    ], dtype=torch.float32)

    theta = torch.tensor([
        0.0,
        0.0,
        0.0,
    ], dtype=torch.float32)

    cov = covariance_2d(scale, theta)

    expected = torch.tensor([
        [[4.0,  0.0],
         [0.0,  9.0]],

        [[1.0,  0.0],
         [0.0, 16.0]],

        [[25.0, 0.0],
         [0.0,  4.0]],
    ], dtype=torch.float32)

    assert cov.shape == (3, 2, 2)
    assert torch.allclose(cov, expected, atol=1e-6)


def test_isotropic_scale_rotation_does_nothing():
    """
    If sx == sy, the Gaussian is circular, so theta should not
    affect the covariance.
    """
    scale = torch.tensor([
        [2.0, 2.0],
        [3.0, 3.0],
        [1.5, 1.5],
    ], dtype=torch.float32)

    theta = torch.tensor([
        0.0,
        math.pi / 4,
        1.234,
    ], dtype=torch.float32)

    cov = covariance_2d(scale, theta)

    expected = torch.tensor([
        [[4.0, 0.0],
         [0.0, 4.0]],

        [[9.0, 0.0],
         [0.0, 9.0]],

        [[2.25, 0.0],
         [0.0, 2.25]],
    ], dtype=torch.float32)

    assert torch.allclose(cov, expected, atol=1e-5)


def test_covariance_is_symmetric():
    """Every valid covariance matrix should be symmetric."""
    scale = torch.tensor([
        [1.0, 2.0],
        [3.0, 0.5],
        [2.5, 4.0],
    ], dtype=torch.float32)

    theta = torch.tensor([
        0.3,
        -0.7,
        2.1,
    ], dtype=torch.float32)

    cov = covariance_2d(scale, theta)

    assert torch.allclose(
        cov,
        cov.transpose(-1, -2),
        atol=1e-6
    )


def test_covariance_is_positive_semidefinite():
    """Eigenvalues of a covariance matrix should be nonnegative."""
    scale = torch.tensor([
        [1.0, 2.0],
        [3.0, 0.5],
        [2.5, 4.0],
    ], dtype=torch.float32)

    theta = torch.tensor([
        0.3,
        -0.7,
        2.1,
    ], dtype=torch.float32)

    cov = covariance_2d(scale, theta)

    eigenvalues = torch.linalg.eigvalsh(cov)

    assert torch.all(eigenvalues >= -1e-6)


def test_gradients_exist():
    """
    Make sure covariance_2d preserves PyTorch's computation graph
    for both scale and theta.
    """
    scale = torch.tensor(
        [[2.0, 3.0]],
        dtype=torch.float32,
        requires_grad=True
    )

    # Use a non-special angle.
    theta = torch.tensor(
        [0.37],
        dtype=torch.float32,
        requires_grad=True
    )

    cov = covariance_2d(scale, theta)

    # Don't use cov.sum(): for R S^2 R^T its sum can have
    # special cancellations. Pick a generic weighted scalar loss.
    weights = torch.tensor(
        [[[1.0, 2.0],
          [3.0, 4.0]]],
        dtype=torch.float32
    )

    loss = (cov * weights).sum()
    loss.backward()

    assert scale.grad is not None
    assert theta.grad is not None

    assert torch.isfinite(scale.grad).all()
    assert torch.isfinite(theta.grad).all()


@pytest.mark.parametrize("N", [1, 2, 10, 100])
def test_output_shape(N):
    scale = torch.rand(N, 2, dtype=torch.float32) + 0.1
    theta = torch.rand(N, dtype=torch.float32)

    cov = covariance_2d(scale, theta)

    assert cov.shape == (N, 2, 2)
    assert cov.dtype == torch.float32